root_path: "data/test_data/clips"
tracker_type: "botsort.yaml"
input_dataset: "data/test_data/annotation.csv"
model_path: "yolov8m-pose.pt"
sliding_window: 30
min_track_length: 5
max_persons: 5
root_output: "results"
